name: Build SXEngine (Windows)

on:
  workflow_dispatch:
  push:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.3

      - name: Setup Haxelib
        run: |
          haxelib setup C:\haxelib

      # ⚡ Cache pour accélérer les builds suivants
      - name: Cache haxelib
        uses: actions/cache@v4
        with:
          path: C:\haxelib
          key: haxelib-${{ runner.os }}-${{ hashFiles('**/hmm.json') }}
          restore-keys: |
            haxelib-${{ runner.os }}

      - name: Install libraries
        run: |
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hxcpp
          haxelib install format
          haxelib install hxp
          haxelib install tjson
          haxelib install hxCodec

      - name: Setup Lime
        run: |
          haxelib run lime setup
          haxelib run lime rebuild windows

      - name: Build Windows
        run: |
          haxelib run lime build windows -release

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: SXEngine-Windows
          path: export/release/windows/bin
